In [1]:
import numpy as np

In [2]:
my_arr = np.array([1,2,3,4,5])

In [3]:
my_arr

array([1, 2, 3, 4, 5])

In [4]:
for i in my_arr:
  print(i)

1
2
3
4
5


In [24]:
# for multi dimentional array

my_arr1 = np.array([[10,12,44],[20,62,60],[56,94,99]])
my_arr1[1,0]
print(my_arr1)

[[10 12 44]
 [20 62 60]
 [56 94 99]]


In [8]:
# slicing

my_arr[0:3]

array([1, 2, 3])

In [11]:
# print last 3 elements

my_arr[-3:]

array([3, 4, 5])

In [12]:
my_arr[3:]

array([4, 5])

In [13]:
my_arr[-3:-1]

array([3, 4])

In [14]:
my_arr[-1:]

array([5])

In [15]:
my_arr[-1]

5

In [17]:
my_arr[2:4]

array([3, 4])

In [27]:
# reshape change the dimention

my_arr1.reshape(-1)

array([10, 12, 44, 20, 62, 60, 56, 94, 99])

In [33]:
my_arr1.reshape(9,1)

array([[10],
       [12],
       [44],
       [20],
       [62],
       [60],
       [56],
       [94],
       [99]])

In [40]:
my_arr2 = np.array([6,7,8,9])
my_arr2

array([6, 7, 8, 9])

In [49]:
my_ar3 = np.concatenate((my_arr, my_arr2))
my_ar3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
x = np.array([[10,20],[30,40]])
x

array([[10, 20],
       [30, 40]])

In [44]:
y = np.array([[50,60],[70,80]])
y

array([[50, 60],
       [70, 80]])

In [47]:
# for column axis = 1, not possible for 1D array

z = np.concatenate((x,y), axis=1)
z

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])