# Numpy basics

In [ ]:
import numpy as np

In [ ]:
# Creating a NumPy array with values 1 to 5

my_arr = np.array([1,2,3,4,5])

In [ ]:
my_arr

array([1, 2, 3, 4, 5])

In [ ]:
# Iterating through the elements of the array and printing each element

for i in my_arr:
  print(i)

1
2
3
4
5


In [ ]:
# for multi dimentional array

my_arr1 = np.array([[10,12,44],[20,62,60],[56,94,99]])
my_arr1[1,0]
print(my_arr1)

[[10 12 44]
 [20 62 60]
 [56 94 99]]


In [ ]:
# slicing array

my_arr[0:3]

array([1, 2, 3])

In [ ]:
# print last 3 elements

my_arr[-3:]

array([3, 4, 5])

In [ ]:
# get elements starting from index 3

my_arr[3:]

array([4, 5])

In [ ]:
# get elements starting from index -3 to -1

my_arr[-3:-1]

array([3, 4])

In [ ]:
# get last element of array

my_arr[-1:]

array([5])

In [ ]:
# Accessing the last element of the array directly

my_arr[-1]

5

In [ ]:
# get elements from index 2 to 3

my_arr[2:4]

array([3, 4])

In [ ]:
# reshape change the dimention

# Reshaping the multi-dimensional array to a 1D array

my_arr1.reshape(-1)

array([10, 12, 44, 20, 62, 60, 56, 94, 99])

In [ ]:
# Reshaping the multi-dimensional array to a 9x1 matrix

my_arr1.reshape(9,1)

array([[10],
       [12],
       [44],
       [20],
       [62],
       [60],
       [56],
       [94],
       [99]])

In [ ]:
my_arr2 = np.array([6,7,8,9])
my_arr2

array([6, 7, 8, 9])

In [ ]:
# Concatenating two arrays to create a new one

my_ar3 = np.concatenate((my_arr, my_arr2))
my_ar3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Creating 2x2 matrices

x = np.array([[10,20],[30,40]])
x

array([[10, 20],
       [30, 40]])

In [ ]:
y = np.array([[50,60],[70,80]])
y

array([[50, 60],
       [70, 80]])

In [ ]:
# for column axis = 1, not possible for 1D array

# Concatenating the matrices horizontally (along columns)

z = np.concatenate((x,y), axis=1)
z

array([[10, 20, 50, 60],
       [30, 40, 70, 80]])